owner = {
    "orders": ["create", "read", "delete", "update"],
    "order_items": ["create", "read", "delete", "update"],
    "notifications": ["create", "read", "delete", "update"],
    "addresses": ["create", "read", "delete", "update"],
    "reports": ["create", "read", "delete", "update"],
    "categories": ["create", "read", "delete", "update"],
    "subcategories": ["create", "read", "delete", "update"],
    "products": ["create", "read", "delete", "update"],
    "product_information": ["create", "read", "delete", "update"],
    "ratings": ["create", "read", "delete", "update"],
    "rating_pictures": ["create", "read", "delete", "update"],
    "wishlists": ["create", "read", "delete", "update"],
    "sizes": ["create", "read", "delete", "update"],
    "colors": ["create", "read", "delete", "update"],
    "measures": ["create", "read", "delete", "update"],
    "product_variants": ["create", "read", "delete", "update"],
    "product_images": ["create", "read", "delete", "update"],
}
