"""fix

Revision ID: 41028fda983f
Revises: add078ee791b
Create Date: 2025-02-22 17:40:15.903160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41028fda983f'
down_revision: Union[str, None] = 'add078ee791b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promotions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('discount', sa.Float(), nullable=False),
    sa.Column('product_limit', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('promotion_product_variants',
    sa.Column('promotion_id', sa.Integer(), nullable=True),
    sa.Column('product_variant_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_variant_id'], ['product_variants.id'], ),
    sa.ForeignKeyConstraint(['promotion_id'], ['promotions.id'], )
    )
    op.add_column('admin_order_items', sa.Column('price_with_discount', sa.DECIMAL(precision=10, scale=2), nullable=True))
    op.add_column('admin_order_items', sa.Column('total_amount_with_discount', sa.DECIMAL(precision=10, scale=2), nullable=True))
    op.add_column('admin_orders', sa.Column('total_amount_with_discount', sa.DECIMAL(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin_orders', 'total_amount_with_discount')
    op.drop_column('admin_order_items', 'total_amount_with_discount')
    op.drop_column('admin_order_items', 'price_with_discount')
    op.drop_table('promotion_product_variants')
    op.drop_table('promotions')
    # ### end Alembic commands ###
