"""fixed

Revision ID: 62e33b022bff
Revises: f4fed10ce199
Create Date: 2025-02-27 19:06:26.390232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62e33b022bff'
down_revision: Union[str, None] = 'f4fed10ce199'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('chat_history_user_id_fkey', 'chat_history', type_='foreignkey')
    op.create_foreign_key(None, 'chat_history', 'admin_users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat_history', type_='foreignkey')
    op.create_foreign_key('chat_history_user_id_fkey', 'chat_history', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
