"""fixed

Revision ID: af740181e4d6
Revises: 004ae867f217
Create Date: 2025-02-24 20:25:31.556872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af740181e4d6'
down_revision: Union[str, None] = '004ae867f217'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('warehouse_subcategories', sa.Column('warehouse_category_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'warehouse_subcategories', 'warehouse_categories', ['warehouse_category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'warehouse_subcategories', type_='foreignkey')
    op.drop_column('warehouse_subcategories', 'warehouse_category_id')
    # ### end Alembic commands ###
